name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install docker app plugin
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export OSTYPE="$(uname | tr A-Z a-z)"
          curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.9.1-beta3/docker-app-${OSTYPE}.tar.gz"
          tar xf "/tmp/docker-app-${OSTYPE}.tar.gz" -C /tmp/
          mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${OSTYPE}" ~/.docker/cli-plugins/docker-app

      - name: Validate and Build Docker App
        run: |
          docker app build dot-base.dockerapp -t ghcr.io/dot-base/dot-base:latest
