name: Docker

on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*

jobs:
  push:
    name: Build and Push Docker App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install docker app plugin
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export OSTYPE="$(uname | tr A-Z a-z)"
          curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.9.1-beta3/docker-app-${OSTYPE}.tar.gz"
          tar xf "/tmp/docker-app-${OSTYPE}.tar.gz" -C /tmp/
          mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${OSTYPE}" ~/.docker/cli-plugins/docker-app

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set app name and version
        run: |
          export IMAGE_ID=ghcr.io/${{ github.repository }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          export VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && export VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && export VERSION=latest

          # Use Docker `latest` tag convention
          [ "$VERSION" == "dev" ] && export VERSION=next

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

      - name: Build app
        run: |
          docker app build dot-base.dockerapp -t $IMAGE_ID:$VERSION

      - name: Push app
        run: |
          docker app push $IMAGE_ID:$VERSION
